project_id = "rfjqqixgevlgjeybeedw"

[functions.aero-groq]
verify_jwt = true

[functions.aero-execute]
verify_jwt = true

[functions.aero-memory]
verify_jwt = true

[functions.aero-presence]
verify_jwt = true
